name: Deploy Infrastructure and Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  setup-s3:
    name: Setup S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform for S3
        working-directory: terraform/s3
        run: terraform init

      - name: Apply Terraform for S3
        working-directory: terraform/s3
        run: terraform apply -auto-approve

  upload-lambda-code:
    name: Upload Lambda Code to S3
    runs-on: ubuntu-latest
    needs: setup-s3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies and package Lambda functions
        run: |
          mkdir -p lambda_package/event_processor
          mkdir -p lambda_package/data_statistics

          cp lambda/event_processor/lambda_function.py lambda_package/event_processor/
          cp lambda/data_statistics/statistics_function.py lambda_package/data_statistics/

          pip install -r requirements.txt -t lambda_package/event_processor/
          pip install -r requirements.txt -t lambda_package/data_statistics/

          cd lambda_package/event_processor
          zip -r ../../event_processor.zip .
          cd ../data_statistics
          zip -r ../../data_statistics.zip .

      - name: Upload Lambda ZIPs to S3
        run: |
          aws s3 cp event_processor.zip s3://device-raw-data-bucket/
          aws s3 cp data_statistics.zip s3://device-raw-data-bucket/

  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    needs: upload-lambda-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: terraform/main
        run: terraform init

      - name: Apply Terraform
        working-directory: terraform/main
        run: terraform apply -auto-approve

  update-lambda-code:
    name: Update Lambda Code
    runs-on: ubuntu-latest
    needs: terraform # Ensures Terraform completes first

    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda Functions
        run: |
          aws lambda update-function-code --function-name event_processor --s3-bucket device-raw-data-bucket --s3-key event_processor.zip
          aws lambda update-function-code --function-name data_statistics --s3-bucket device-raw-data-bucket --s3-key data_statistics.zip
